const TYPES = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_ALL_FROM_CART: "DELETE_ALL_FROM_CART",
    DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
    CALCULATE_TOTAL_PRICE: "CALCULATE_TOTAL_PRICE",
}

export default TYPES;